dre_django/authapp/urls.py
# Global Imports
from django.conf.urls import url
from django.contrib.auth import views as auth_views

# Local Imports:
from authapp import views as authapp_views

urlpatterns = [
    # Authentication
    url(r'^login/$', authapp_views.do_login,
        {'template_name': 'login.html'}, name='login'),

    url(r'^logout/$', authapp_views.do_logout, name='logout'),

    # Registration urls
    url(r'^register/$', authapp_views.registration, name='registration'),

    # Personal data
    url(r'^personal_data/$', authapp_views.personal_data, name='personal_data'),
]

urlpatterns += [
    # Change password
    url(r'^password_change/$', auth_views.PasswordChangeView.as_view(
        template_name='password_change_form.html'),
        name='password_change'),
    url(r'^password_change/done/$', auth_views.PasswordChangeDoneView.as_view(
        template_name='password_change_done.html'),
        name='password_change_done'),

    # Password reset
    url(r'^password_reset/$', auth_views.PasswordResetView.as_view(
        template_name='password_reset.html',
        email_template_name='password_reset_email.txt',
        subject_template_name='password_reset_subject.txt'),
        name='password_reset'),
    url(r'^password_reset_done/done/$', auth_views.PasswordResetDoneView.as_view(
        template_name='password_reset_done.html'),
        name='password_reset_done'),
    url(r'^password_reset/confirm/(?P<uidb64>[0-9A-Za-z]{1,13})/'
        r'(?P<token>.+)/$',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='password_reset_confirm.html'),
        name='password_reset_confirm'),
    url(r'^password_reset/complete/$', auth_views.PasswordResetCompleteView.as_view(
        template_name='password_reset_complete.html'),
        name='password_reset_complete'),
]

dre_django/dre_django/urls.py
# Global Imports:
from django.conf import settings
from django.conf.urls import include, url
from django.contrib.sitemaps import views as sitemap_views
from django.views.generic import TemplateView

# Local Imports:
from dre_django.sitemap import StaticViewSitemap
from dreapp.sitemap import DocumentSitemap

from dreapp import views

urlpatterns = [
    # Index:
    url(r'^$', views.search),

    # About:
    url(r'^about/',
        TemplateView.as_view(template_name='about.html'),
        name='about'),

    # Help:
    url(r'^help/',
        TemplateView.as_view(template_name='help.html'),
        name='help'),

    # FAQ:
    url(r'^faq/',
        TemplateView.as_view(template_name='faq.html'),
        name='faq'),

    # Not implemented:
    url(r'^not_implemented/',
        TemplateView.as_view(template_name='not_implemented.html'),
        name='not_implemented'),

    # Authentication and registration
    url(r'^auth/', include('authapp.urls')),

    # Bookmarks
    url(r'^bookmark/', include('bookmarksapp.urls')),

    # Tags
    url(r'^tag/', include('tagsapp.urls')),

    # Notes
    url(r'^notes/', include('notesapp.urls')),

    # Settings
    url(r'settings/', include('settingsapp.urls')),

    # Captcha
    url(r'^captcha/', include('captcha.urls')),

    # dreapp
    url(r'^dre/', include('dreapp.urls')),
]


sitemaps = {
    'static': StaticViewSitemap,
    'documents': DocumentSitemap,
}

urlpatterns += [
    url(r'^sitemap\.xml$', sitemap_views.index, {'sitemaps': sitemaps}),
    url(r'^sitemap-(?P<section>.+)\.xml$', sitemap_views.sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
]


if settings.DEBUG:
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    urlpatterns += staticfiles_urlpatterns()

dre_django/dreapp/urls.py
# Global Imports:
from dreapp.syndication import LatestEntriesFeed
from django.conf.urls import url
from django.views.generic import TemplateView

# Local Imports
from dreapp import views

urlpatterns = [
    # Browsing index:
    url(r'^data/$', views.browse, name='browse'),

    # Today's results:
    url(r'^data/hoje/$', views.today_results, name='today_results'),

    # Browse by day:
    url(r'^data/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/$',
        views.browse_day, name='browse_day'),

    # Document display
    url(r'^(?P<docid>\d+)/[a-zA-Z0-9\(\)ºª\.\-/_]+$',
        views.document_display, name='document_display'),
    url(r'^(?P<docid>\d+)/$',
        views.document_redirect, name='document_redirect'),

    # Document display (JSON)
    url(r'^(?P<docid>\d+)\.json$', views.document_json, name='document_json'),

    # Document display (JSON-LD)
    url(r'^(?P<docid>\d+)\.jsonld$', views.document_jsonld, name='document_jsonld'),

    # Document display (Original PDF)
    url(r'^(?P<docid>\d+)\.dre\.pdf$',
        views.document_org_pdf, name='document_org_pdf'),

    # Display the bookmarked documents
    url(r'^marcador/(?P<userid>\d+)/$',
        views.bookmark_display, name='bookmark_display'),

    # Top documents
    url(r'^top/$', views.top, name='top'),

    # Last documents
    url(r'^last/$', views.last, name='last'),

    # Generate dynamic JS
    url(r'^view_js\.js', views.view_js, name='view_js'),
]

##
# Feeds
##


urlpatterns += [
    # Latest feeds
    url(r'^rss/$', LatestEntriesFeed(), name='rss'),

    # Feed help page:
    url(r'^rss/help/$',
        TemplateView.as_view(template_name='rss_help.html'),
        name='rss_help'),
]

dre_django/authapp/models.py
from django.db import models


class AccessAttempt(models.Model):
    ip_address = models.GenericIPAddressField('IP Address')
    failures = models.PositiveIntegerField('Failed Logins', default=0)

dre_django/authapp/forms.py
"""Authentication forms"""

from django.conf import settings
from django.contrib.auth.forms import AuthenticationForm
from django.forms.utils import ErrorList
from django import forms

from captcha.fields import CaptchaField

# Local


class AuthFormPersistent(AuthenticationForm):
    def __init__(self, *args, **kargs):
        show_captcha = False
        if 'show_captcha' in kargs:
            show_captcha = kargs['show_captcha']
            del kargs['show_captcha']

        if show_captcha:
            self.base_fields['captcha'] = CaptchaField(label='Humano?')
        else:
            if 'captcha' in self.base_fields:
                del self.base_fields['captcha']
        super(AuthFormPersistent, self).__init__(*args, **kargs)

    autologin = forms.BooleanField(
        label='Login automatico?',
        required=False)

# Registration forms


ALLOWEDCHARS = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRTSUVWXYZ0123456789'


class RegistrationForm(forms.Form):
    '''Registration form for a new user
    '''
    username = forms.CharField(
        label='Nome de utilizador',
        required=True,
        max_length=30,)
    email = forms.EmailField(
        label='Email',
        required=False,
        help_text='Não é obrigatório')
    password_1 = forms.CharField(
        widget=forms.PasswordInput(render_value=False),
        label='Senha',
        required=True)
    password_2 = forms.CharField(
        widget=forms.PasswordInput(render_value=False),
        label='Confirmar senha',
        required=True)
    captcha = CaptchaField(label='Humano?')

    # The validation battery
    def clean_username(self):
        username = self.cleaned_data.get('username')
        for c in username:
            if c not in ALLOWEDCHARS:
                raise forms.ValidationError('O nome de utilizador não admite '
                                            'espaços, ou caracteres com acentos.')
        return username

    def clean(self):
        cleaned_data = self.cleaned_data

        password_1 = cleaned_data.get('password_1')
        password_2 = cleaned_data.get('password_2')

        if 'password_2' not in self._errors:
            if password_1 != password_2:
                msg = 'As senhas não coincidem.'
                self._errors['password_2'] = ErrorList([msg])
            if len(password_1) < settings.PASSWORD_MIN_SIZE:
                msg = 'A senha é muito curta (minimo %s).' % settings.PASSWORD_MIN_SIZE
                self._errors['password_2'] = ErrorList([msg])
            if len(password_1) > settings.PASSWORD_MAX_SIZE:
                msg = 'A senha é muito longa (maximo %s).' % settings.PASSWORD_MAX_SIZE
                self._errors['password_2'] = ErrorList([msg])

        return cleaned_data


class PersonalDataForm(forms.Form):
    '''Change user's personal data
    '''
    first_name = forms.CharField(
        label='Primeiro nome',
        required=False,
        max_length=30,)
    last_name = forms.CharField(
        label='Último nome',
        required=False,
        max_length=30,)
    email = forms.EmailField(
        label='Email',
        required=False, )

dre_django/authapp/views.py
'''Authentication forms'''

# Global imports
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, REDIRECT_FIELD_NAME
from django.contrib.auth.models import User
from django.forms.utils import ErrorList
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.contrib.auth import login, logout
from django.http import Http404
from django.core.exceptions import MultipleObjectsReturned
import time

# Local imports
from .forms import AuthFormPersistent, RegistrationForm, PersonalDataForm
from .models import AccessAttempt


@csrf_protect
@never_cache
def do_login(request, template_name='login.html',
             redirect_field_name=REDIRECT_FIELD_NAME,
             authentication_form=AuthFormPersistent):
    '''Displays the login form and handles the login action.'''

    # For each IP create a log line with login information
    remote_ip = request.META['HTTP_X_FORWARDED_FOR']
    try:
        obj, created = AccessAttempt.objects.get_or_create(ip_address=remote_ip)
    except MultipleObjectsReturned:
        # TODO: on some circumstances we will have more than one entry on the access attempt table
        # this is a bug.
        raise Http404

    show_captcha = (obj.failures >= settings.FAILURE_LIMIT)

    redirect_to = request.GET.get(redirect_field_name, '')

    if request.method == "POST":
        form = authentication_form(data=request.POST, show_captcha=show_captcha)

        if form.is_valid():
            # Light security check -- make sure redirect_to isn't garbage.
            if not redirect_to or '//' in redirect_to or ' ' in redirect_to:
                redirect_to = settings.LOGIN_REDIRECT_URL

            login(request, form.get_user())

            if request.session.test_cookie_worked():
                request.session.delete_test_cookie()
            if form.cleaned_data['autologin']:
                request.session.set_expiry(settings.SESSION_COOKIE_AGE)
            else:
                request.session.set_expiry(0)

            # Resets the failed attempts
            obj.delete()

            return HttpResponseRedirect(redirect_to)
        else:
            obj.failures += 1
            if (obj.failures > settings.FAILURE_LIMIT) and not show_captcha:
                show_captcha = True
                form = authentication_form(data=request.POST, show_captcha=show_captcha)
            obj.save()
    else:
        form = authentication_form(request, show_captcha=show_captcha)

    request.session.set_test_cookie()

    if show_captcha:
        # Time penalty for multiple failed logins
        time.sleep(5)

    return render(request, template_name, {
        'form': form,
        'auth_error': '__all__' in form.errors,
        redirect_field_name: redirect_to,
    })

# TODO: when loging out on a restricted area we should be redirected to the
# index page instead of the "permission denied" page.


def do_logout(request, next_page=None, template_name='logout.html',
              redirect_field_name=REDIRECT_FIELD_NAME):
    '''Logs out the user and displays 'You are logged out' message.'''

    logout(request)
    if next_page is None:
        redirect_to = request.GET.get(redirect_field_name, '')
        if redirect_to:
            return HttpResponseRedirect(redirect_to)
        else:
            return render(request, template_name, {
                'title': 'Logged out'
            })
    else:
        # Redirect to this page until the session has been cleared.
        return HttpResponseRedirect(next_page or request.path)

# Registration views


@csrf_protect
@never_cache
def registration(request):
    '''User registration.'''
    context = {}

    redirect_to = request.GET.get(REDIRECT_FIELD_NAME, '')
    context['next'] = redirect_to

    if request.method == 'POST':
        form = RegistrationForm(request.POST.copy())
        if form.is_valid():
            data = form.cleaned_data

            # Check if user exists and creates if not
            user = User.objects.filter(username=data['username'])
            if user:
                form._errors['username'] = ErrorList(
                    ['Um utilizador com o nome %s já existe' % data['username']])
                context['form'] = form
                return render(request, 'registration.html', context)

            # Light security check -- make sure redirect_to isn't garbage.
            if not redirect_to or '//' in redirect_to or ' ' in redirect_to:
                redirect_to = settings.LOGIN_REDIRECT_URL

            new_user = User.objects.create_user(data['username'], data['email'], data['password_1'])

            # Login user and send to origin page
            new_user_auth = authenticate(username=data['username'], password=data['password_1'])
            login(request, new_user_auth)
            return HttpResponseRedirect(redirect_to)
        else:
            context['form'] = form
    else:
        form = RegistrationForm()
        context['form'] = form

    return render(request, 'registration.html', context)


@login_required
def personal_data(request):
    '''Personal data'''
    context = {}
    context['saved'] = False
    user = request.user

    if request.method == 'POST':
        form = PersonalDataForm(request.POST.copy())
        if form.is_valid():
            user.first_name = form.cleaned_data['first_name']
            user.last_name = form.cleaned_data['last_name']
            user.email = form.cleaned_data['email']
            user.save()
            context['saved'] = True
    else:
        form = PersonalDataForm({
            'first_name': user.first_name,
            'last_name': user.last_name,
            'email': user.email})

    context['form'] = form

    return render(request, 'personal_data.html', context)

dre_django/authapp/templates/login.html
{% extends "base.html" %}
{% load static %}

{% block title %}Diários da República - Login{% endblock %}

{% block header %}
  <meta name="robots" content="noindex, nofollow">
  <meta name="keywords" content="procura,diplomas,documentos,diário da república">
  <meta name="description" content="Procura de diplomas no Diário da República Electrónico - página de login">
  <meta property="og:title" content="Diários da República - Login">
  <meta property="og:type" content="website">
  <meta property="og:url" content="{{ SITE_URL }}">
  <meta property="og:image" content="{{ SITE_URL }}{% static 'img/esfera_armilar_200.png' %}">
  <meta property="og:site_name" content="Diários da República - Versão do cidadão">
  <meta property="fb:admins" content="webmaster@tretas.org">
  <meta property="og:description" content="Procura de diplomas no Diário da República">
{% endblock %}

{% block body_content %}

  <form id="alone" method="post" action="{% url 'login' %}{% if next %}?next={{ next }}{% endif %}">{% csrf_token %}
  <h1>Autenticação</h1>
    {% if auth_error %}
    <p class="warning">O seu nome e/ou palavra-passe estão errados. Por favor tente de novo.
    </p>
    {% endif %}
    <p><label for="id_username">Utilizador:</label> {{ form.username }}</p>
    <p><label for="id_password">Palavra-Passe:</label> {{ form.password }}</p>
    <p><label for="id_autologin">Login automatico?</label> {{ form.autologin }}</p>
    <p>Esqueceu-se da sua palavra-passe? Clique <a href="{% url 'password_reset' %}">aqui</a>.</p>
    {% if form.captcha %}
      {{ form.captcha }}<br>{{ form.captcha.errors }}
    {% endif %}
    <div class="center_text">
      <button style="width:6em" type="submit" value="Submit">Entrar</button>
    </div>
    <input type="hidden" name="next" value="{{ next }}" />
    <input type="submit" style="width:0px;height:0px;border:none;padding:0px;font-size:0px">
  </form>
{% endblock %}

dre_django/authapp/templates/logout.html
{% extends "base.html" %}
{% load static %}

{% block title %}Sair{% endblock %}

{% block header %}
  <meta name="robots" content="noindex, nofollow">
  <meta name="keywords" content="procura,diplomas,documentos,diário da república">
  <meta name="description" content="Procura de diplomas no Diário da República Electrónico - página de logout">
  <meta property="og:title" content="Diários da República - Logout">
  <meta property="og:type" content="website">
  <meta property="og:url" content="{{ SITE_URL }}">
  <meta property="og:image" content="{{ SITE_URL }}{% static 'img/esfera_armilar_200.png' %}">
  <meta property="og:site_name" content="Diários da República - Versão do cidadão">
  <meta property="fb:admins" content="webmaster@tretas.org">
  <meta property="og:description" content="Procura de diplomas no Diário da República">
{% endblock %}

{% block body_content %}

<h1>Saiu do dre.tretas.org!</h1>

{% endblock %}

dre_django/authapp/templates/password_change_done.html
{% extends "base.html" %}
{% load static %}

{% block title %}Mudar Senha{% endblock %}

{% block header %}
  <meta name="robots" content="noindex, nofollow">
  <meta name="keywords" content="procura,diplomas,documentos,diário da república">
  <meta name="description" content="Procura de diplomas no Diário da República Electrónico - página de mudança de palavra chave">
  <meta property="og:title" content="Diários da República - Mudança de palavra chave">
  <meta property="og:type" content="website">
  <meta property="og:url" content="{{ SITE_URL }}">
  <meta property="og:image" content="{{ SITE_URL }}{% static 'img/esfera_armilar_200.png' %}">
  <meta property="og:site_name" content="Diários da República - Versão do cidadão">
  <meta property="fb:admins" content="webmaster@tretas.org">
  <meta property="og:description" content="Procura de diplomas no Diário da República - página de mudança de palavra chave">
{% endblock %}

{% block body_content %}
<h1>Mudar Senha</h1>

<p>Senha mudada com sucesso.
{% endblock %}

dre_django/authapp/templates/password_change_form.html
{% extends "settings.html" %}
{% load static %}

{% block title %}Mudar Palavra-Passe{% endblock %}

{% block header %}
  <meta name="robots" content="noindex, nofollow">
  <link rel="stylesheet" type="text/css" href="/static/css/settings.css">
  <meta name="keywords" content="procura,diplomas,documentos,diário da república">
  <meta name="description" content="Procura de diplomas no Diário da República Electrónico - página de mudança de palavra chave">
  <meta property="og:title" content="Diários da República - Mudança de palavra chave">
  <meta property="og:type" content="website">
  <meta property="og:url" content="{{ SITE_URL }}">
  <meta property="og:image" content="{{ SITE_URL }}{% static 'img/esfera_armilar_200.png' %}">
  <meta property="og:site_name" content="Diários da República - Versão do cidadão">
  <meta property="fb:admins" content="webmaster@tretas.org">
  <meta property="og:description" content="Procura de diplomas no Diário da República - página de mudança de palavra chave">
{% endblock %}

{% block content_column %}
    <h1>Mudar Palavra-Passe</h1>
    <form id="settings" method="post" action="{% url 'password_change' %}{% if next %}?next={{ next }}{% endif %}">{% csrf_token %}
        {{ form.as_p }}
        <div class="center_text">
          <button style="width:12em" type="submit" value="Submit">Mudar Palavra-Passe</button>
        </div>
    </form>
{% endblock %}

dre_django/authapp/templates/password_reset.html
{% extends "base.html" %}
{% load static %}

{% block title %}Recuperar Palavra-Passe{% endblock %}

{% block header %}
  <meta name="robots" content="noindex, nofollow">
  <meta name="keywords" content="procura,diplomas,documentos,diário da república">
  <meta name="description" content="Procura de diplomas no Diário da República Electrónico - página de mudança de palavra chave">
  <meta property="og:title" content="Diários da República - Mudança de palavra chave">
  <meta property="og:type" content="website">
  <meta property="og:url" content="{{ SITE_URL }}">
  <meta property="og:image" content="{{ SITE_URL }}{% static 'img/esfera_armilar_200.png' %}">
  <meta property="og:site_name" content="Diários da República - Versão do cidadão">
  <meta property="fb:admins" content="webmaster@tretas.org">
  <meta property="og:description" content="Procura de diplomas no Diário da República - página de mudança de palavra chave">
{% endblock %}

{% block body_content %}
    <h1>Recuperar Palavra-Passe</h1>
    <div class="center_text">
      <p>Para recuperar a sua palavra-passe indique por favor o endereço de
      correio electrónico que usou para se registar no site:
      <form method="post" action="{% url 'password_reset' %}">{% csrf_token %}
        <table>
          {{ form }}
          <tr>
            <td colspan=2>
              <div class="center_text">
                <button style="width:12em" type="submit" value="Submit">Recuperar<br>Palavra-Passe</button>
              </div>
            </td>
          </tr>
        </table>
      </form>
    </div>
{% endblock %}

dre_django/authapp/templates/password_reset_complete.html
{% extends "base.html" %}
{% load static %}

{% block title %}Recuperar Palavra-Passe{% endblock %}

{% block header %}
  <meta name="robots" content="noindex, nofollow">
  <meta name="keywords" content="procura,diplomas,documentos,diário da república">
  <meta name="description" content="Procura de diplomas no Diário da República Electrónico - página de mudança de palavra chave">
  <meta property="og:title" content="Diários da República - Mudança de palavra chave">
  <meta property="og:type" content="website">
  <meta property="og:url" content="{{ SITE_URL }}">
  <meta property="og:image" content="{{ SITE_URL }}{% static 'img/esfera_armilar_200.png' %}">
  <meta property="og:site_name" content="Diários da República - Versão do cidadão">
  <meta property="fb:admins" content="webmaster@tretas.org">
  <meta property="og:description" content="Procura de diplomas no Diário da República - página de mudança de palavra chave">
{% endblock %}

{% block body_content %}
    <h1>Recuperar Palavra-Passe</h1>
    <div class="center_text">
      <p>Palavra-passe mudada com êxito! Pode agora <a href="{% url 'login' %}">entrar</a>
      no sistema.
    </div>
{% endblock %}

dre_django/authapp/templates/password_reset_confirm.html
{% extends "base.html" %}
{% load static %}

{% block title %}Recuperar Palavra-Passe{% endblock %}

{% block header %}
  <meta name="robots" content="noindex, nofollow">
  <meta name="keywords" content="procura,diplomas,documentos,diário da república">
  <meta name="description" content="Procura de diplomas no Diário da República Electrónico - página de mudança de palavra chave">
  <meta property="og:title" content="Diários da República - Mudança de palavra chave">
  <meta property="og:type" content="website">
  <meta property="og:url" content="{{ SITE_URL }}">
  <meta property="og:image" content="{{ SITE_URL }}{% static 'img/esfera_armilar_200.png' %}">
  <meta property="og:site_name" content="Diários da República - Versão do cidadão">
  <meta property="fb:admins" content="webmaster@tretas.org">
  <meta property="og:description" content="Procura de diplomas no Diário da República - página de mudança de palavra chave">
{% endblock %}

{% block body_content %}
  {% if validlink %}
    <h1>Recuperar Palavra-Passe</h1>
    <div class="center_text">
      <p>Indique, por favor, a sua nova palavra-passe:</p>
      <form method="post">{% csrf_token %}
        <table>
          {{ form }}
          <tr>
            <td colspan=2>
              <div class="center_text">
                <button style="width:12em" type="submit" value="Submit">Mudar<br>Palavra-Passe</button>
              </div>
            </td>
          </tr>
        </table>
      </form>
    </div>
  {% else %}
    <h1>Ligação inválida</h1>
  {% endif %}
{% endblock %}

dre_django/authapp/templates/password_reset_done.html
{% extends "base.html" %}
{% load static %}

{% block title %}Recuperar Palavra-Passe{% endblock %}

{% block header %}
  <meta name="robots" content="noindex, nofollow">
  <meta name="keywords" content="procura,diplomas,documentos,diário da república">
  <meta name="description" content="Procura de diplomas no Diário da República Electrónico - página de mudança de palavra chave">
  <meta property="og:title" content="Diários da República - Mudança de palavra chave">
  <meta property="og:type" content="website">
  <meta property="og:url" content="{{ SITE_URL }}">
  <meta property="og:image" content="{{ SITE_URL }}{% static 'img/esfera_armilar_200.png' %}">
  <meta property="og:site_name" content="Diários da República - Versão do cidadão">
  <meta property="fb:admins" content="webmaster@tretas.org">
  <meta property="og:description" content="Procura de diplomas no Diário da República - página de mudança de palavra chave">
{% endblock %}

{% block body_content %}
    <h1>Recuperar Palavra-Passe</h1>
    <div class="center_text">
      <p>Foi enviada uma mensagem com as instruções necessárias para recuperar
      a sua palavra-passe.
    </div>
{% endblock %}

dre_django/authapp/templates/personal_data.html
{% extends "settings.html" %}
{% load static %}

{% block title %}Dados pessoais{% endblock %}

{% block header %}
  <meta name="robots" content="noindex, nofollow">
  <meta name="keywords" content="procura,diplomas,documentos,diário da república">
  <meta name="description" content="Procura de diplomas no Diário da República Electrónico - Dados pessoais">
  <meta property="og:title" content="Diários da República - Dados pessoais">
  <meta property="og:type" content="website">
  <meta property="og:url" content="{{ SITE_URL }}">
  <meta property="og:image" content="{{ SITE_URL }}{% static 'img/esfera_armilar_200.png' %}">
  <meta property="og:site_name" content="Diários da República - Versão do cidadão">
  <meta property="fb:admins" content="webmaster@tretas.org">
  <meta property="og:description" content="Procura de diplomas no Diário da República - Dados pessoais">
{% endblock %}

{% block content_column %}

    <h1>Dados Pessoais</h1>

    <form id="settings" method="post" action="{% url 'personal_data' %}{% if next %}?next={{ next }}{% endif %}">{% csrf_token %}
        {{ form.as_p }}
        <div class="center_text">
          <button style="width:12em" type="submit" value="Submit">Salvar dados pessoais</button>
          {% if saved %}<p>Dados guardados.</p>{% endif %}
        </div>
    </form>
{% endblock %}

dre_django/authapp/templates/registration.html
{% extends "base.html" %}
{% load static %}

{% block title %}Registar{% endblock %}

{% block header %}
  <meta name="robots" content="noindex, nofollow">
  <meta name="keywords" content="procura,diplomas,documentos,diário da república">
  <meta name="description" content="Procura de diplomas no Diário da República Electrónico - Registo de nova conta">
  <meta property="og:title" content="Diários da República - Registo de nova conta">
  <meta property="og:type" content="website">
  <meta property="og:url" content="{{ SITE_URL }}">
  <meta property="og:image" content="{{ SITE_URL }}{% static 'img/esfera_armilar_200.png' %}">
  <meta property="og:site_name" content="Diários da República - Versão do cidadão">
  <meta property="fb:admins" content="webmaster@tretas.org">
  <meta property="og:description" content="Procura de diplomas no Diário da República - Registo de nova conta">
{% endblock %}

{% block body_content %}
<div class="center_text">
<h1>Registar</h1>

<form method="post" action="{% url 'registration' %}{% if next %}?next={{ next }}{% endif %}">{% csrf_token %}
<table>
  <tr>
    <th>{{ form.username.label }}</th>
    <td>
      {{ form.username }}
      {{ form.username.errors }}
    </td>
  </tr>
  <tr>
    <th>{{ form.password_1.label }}</th>
    <td>{{ form.password_1 }}</td>
  </tr>
  <tr>
    <th>{{ form.password_2.label }}</th>
    <td>
      {{ form.password_2 }}
      {{ form.password_2.errors }}
    </td>
  </tr>
  <tr>
    <th>{{ form.email.label }} <cite>({{ form.email.help_text }})</cite></th>
    <td>
      {{ form.email }}
      {{ form.email.errors }}
    </td>
  </tr>
  <tr>
    <td colspan=2>
      {{ form.captcha }}
      {{ form.captcha.errors }}
    </td>
  </tr>
  <tr>
    <th colspan=2>
      <button style="width:8em" type="submit" value="Submit">Registar</button>
      <input type="hidden" name="next" value="{{ next }}">
    </th>
  </tr>
</table>
</form>
</div>
{% endblock %}